// app/pages/about.vue
<script setup lang="ts">
import type { ProjectsCollectionItem } from "@nuxt/content";
import { useDateFormat } from "@vueuse/core";

const page = (await useAsyncData(() => queryCollection("content").where("path", "=", "/about").first())).data.value!;

useSiteHead(page);

// get all business roles
const roles = (await useAsyncData(() => queryCollection("roles").order("date", "DESC").all())).data.value!;

const business = roles.filter((role) => role.context?.includes("business"));

// get projects associated with each role
const roleProjects = (
  await useAsyncData(() =>
    queryCollection("projects")
      .select("title", "date", "stem", "role")
      .where(
        "role",
        "IN",
        business.map((r) => r.stem.split("/").pop()),
      )
      .order("date", "DESC")
      .all(),
  )
).data.value!;

// join projects to roles
for (const role of business) {
  role.meta.projects = roleProjects.filter((p) => role.stem.endsWith(p.role));
}

// roles older than this are "additional experience"
const oldRoles = business.findIndex((role) => role.date < "2007-01-01");

// get all education roles
const education = roles.filter((role) => role.context?.includes("educational"));

// get all honors
const honors = (await useAsyncData(() => queryCollection("honors").order("date", "DESC").all())).data.value!;

// get all awards
const awards = (await useAsyncData(() => queryCollection("awards").order("date", "DESC").all())).data.value!;

// get projects associated with each award
const awardProjects = (
  await useAsyncData(() =>
    queryCollection("projects")
      .select("title", "stem")
      .where(
        "stem",
        "IN",
        awards.map((a) => `projects/${a.project.split("/").pop()}`),
      )
      .all(),
  )
).data.value!;

// join projects to awards
for (const award of awards) {
  award.meta.project = awardProjects.find((p) => p.stem.endsWith(award.project));
}

// get all volunteer roles
const volunteer = roles.filter((role) => role.context?.includes("volunteer"));

const printOnly = "hidden print:block";
const section = "mt-8 print:mt-0";
const grid = "grid grid-cols-4";
const colsL = "col-span-4 md:col-span-1";
const colsR = "col-span-4 md:col-span-3";
const metaRow = "flex flex-col md:flex-row";
const metaLeft = "flex-1";
const metaRight = "flex-shrink-0";
</script>

<template>
  <div class="prose-custom">
    <div :class="grid">
      <div :class="colsL">
        <div :class="printOnly">
          <h4>Josh Santangelo</h4>
          <h6><a href="mailto:josh@endquote.com" class="no-underline">josh@endquote.com</a></h6>
          <h6><a href="https://endquote.com" class="no-underline">endquote.com</a></h6>
          <h6><a href="tel:+12062295674" class="no-underline">+1 (206) 229-5674</a></h6>
        </div>
      </div>
      <div :class="colsR">
        <h2 :class="['print:mt-4', 'mb-0']">{{ page.description }}</h2>
      </div>
    </div>

    <div :class="section">
      <div v-for="(role, i) in business" :key="role.stem" :class="grid">
        <div :class="colsL" v-if="i < oldRoles">
          <template v-if="i === 0">
            <h2>Experience</h2>
          </template>
        </div>
        <div :class="colsR" v-if="i < oldRoles">
          <h3 v-if="i === 0 || roles[i - 1]!.company !== role.company">{{ role.company }}</h3>
          <div :class="metaRow">
            <div :class="metaLeft">
              <NuxtLink v-if="(role.meta.projects as ProjectsCollectionItem[]).length" :to="role.stem">
                <strong>{{ role.title }}</strong></NuxtLink
              ><strong v-else>{{ role.title }}</strong>
            </div>
            <div :class="metaRight">
              {{ role.location }}, {{ useDateFormat(role.date, "YYYY") }}-<template v-if="role.end">{{
                useDateFormat(role.end, "YYYY")
              }}</template
              ><template v-else>present</template>
            </div>
          </div>

          <ContentRenderer :value="role" />
        </div>
      </div>
    </div>

    <div :class="section">
      <div v-for="(role, i) in business" :key="role.stem" :class="grid">
        <div :class="colsL" v-if="i >= oldRoles">
          <template v-if="i === oldRoles">
            <h2>Additional Experience</h2>
          </template>
        </div>
        <div :class="colsR" v-if="i >= oldRoles">
          <h3 v-if="i === 0 || roles[i - 1]!.company !== role.company">{{ role.company }}</h3>
          <div :class="metaRow">
            <div :class="metaLeft">
              <NuxtLink v-if="(role.meta.projects as ProjectsCollectionItem[]).length" :to="role.stem">
                <strong>{{ role.title }}</strong></NuxtLink
              ><strong v-else>{{ role.title }}</strong>
            </div>
            <div :class="metaRight">
              {{ role.location }}
            </div>
          </div>

          <ContentRenderer :value="role" />
        </div>
      </div>
    </div>

    <div :class="section">
      <div v-for="(edu, i) in education" :key="edu.stem" :class="grid">
        <div :class="colsL">
          <template v-if="i === 0">
            <h2>Education</h2>
          </template>
        </div>
        <div :class="colsR">
          <h3>{{ edu.company }}</h3>
          <div :class="metaRow">
            <div :class="metaLeft">
              <strong>{{ edu.title }}</strong>
            </div>
            <div :class="metaRight">
              {{ edu.location }}
            </div>
          </div>

          <ContentRenderer :value="edu" />
        </div>
      </div>
    </div>

    <div :class="section">
      <div v-for="(honor, i) in honors" :key="honor.stem" :class="grid">
        <div :class="colsL">
          <template v-if="i === 0">
            <h2>Honors</h2>
          </template>
        </div>
        <div :class="colsR">
          <div :class="metaRow">
            <div :class="metaLeft">
              <strong>{{ honor.title }}</strong>
            </div>
            <div :class="metaRight">{{ honor.company }}, {{ useDateFormat(honor.date, "YYYY") }}</div>
          </div>

          <ContentRenderer :value="honor" />
        </div>
      </div>
    </div>

    <div :class="[grid, section]">
      <div :class="colsL">
        <h2>Awards</h2>
      </div>
      <div :class="colsR">
        <ul>
          <li v-for="(award, i) in awards" :key="award.stem">
            <template v-if="award.link">
              <NuxtLink :to="award.link">{{ award.title }}</NuxtLink>
            </template>
            <template v-else>
              {{ award.title }}
            </template>
            - {{ award.company }},
            <NuxtLink :to="(award.meta.project as ProjectsCollectionItem).stem">{{
              (award.meta.project as ProjectsCollectionItem).title
            }}</NuxtLink
            >, {{ useDateFormat(award.date, "YYYY") }}
          </li>
        </ul>
      </div>
    </div>

    <div :class="[grid, section]">
      <div :class="colsL">
        <h2>Volunteering</h2>
      </div>
      <div :class="colsR">
        <ul>
          <li v-for="role in volunteer" :key="role.stem">
            {{ role.description }},
            <template v-if="role.link">
              <NuxtLink :to="role.link">{{ role.company }}</NuxtLink>
            </template>
            <template v-else> {{ role.company }} </template>, {{ useDateFormat(role.date, "YYYY") }}
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

// pages/about.tsx
import { GetStaticProps } from "next";
import { FC } from "react";
import { Col, Row } from "react-bootstrap";
import { PrintLink } from "../components/PrintLink";
import { Experience, Role } from "../data/experience";
import { query as projectQuery } from "../data/projects";
import { year } from "../utils/formatDate";
import { htmlToReact } from "../utils/htmlToReact";
import css from "./about.module.scss";

function RoleRow({ role, date = true }: { role: Role; date: boolean }) {
  return (
    <div className="mb-4">
      <h5>{htmlToReact(role.company)}</h5>
      <Row className="mb-1">
        <Col xs="12" sm="6">
          <strong>{htmlToReact(role.title)}</strong>
        </Col>
        <Col xs="12" sm="6" className={`text-left text-sm-right`}>
          {role.location}
          <span className={!date ? "d-none" : ""}>
            , {year(role.start)}-{role.end ? year(role.end) : "present"}
          </span>
        </Col>
      </Row>
      <p>{htmlToReact(role.desc)}</p>
      <ul className={!role.accomplishments.length ? "d-none" : ""}>
        {role.accomplishments.map((a, i) => (
          <li key={i}>{htmlToReact(a)}</li>
        ))}
      </ul>
    </div>
  );
}

type Props = {
  exp: Experience;
  strings: any;
};

export const About: FC<Props> = ({ strings, exp }) => {
  return (
    <div className="content">
      <Row>
        <Col sm="12" md="3" lg="3">
          <h4 className={`${css.headline} d-none d-print-block`}>
            Josh Santangelo
          </h4>
          <h6 className={css.email}>
            <a className={css.noline} href="mailto:josh@endquote.com">
              josh@endquote.com
            </a>
          </h6>
          <h6 className={`${css.email} ${css.webLink}`}>
            <a className={css.noline} href="https://endquote.com">
              www.endquote.com
            </a>
          </h6>
          <h6 className={`${css.email} ${css.webLink}`}>
            <a className={css.noline} href="tel:+12062295674">
              +1 (206) 229-5674
            </a>
          </h6>
        </Col>
        <Col sm="12" md="9" lg="9">
          <h4 className={css.headline}>{htmlToReact(strings.headline)}</h4>
          {strings.summary.map((s: string, i: number) => (
            <p key={i}>{htmlToReact(s)}</p>
          ))}
        </Col>
      </Row>
      <Row className="mb-4">
        <Col sm="12" md="3" lg="3">
          <h5>
            <strong>{strings.skills}</strong>
          </h5>
        </Col>
        <Col sm="12" md="9" lg="9">
          <Row>
            <Col sm="12" md="12" lg="6">
              <ul className="mb-0">
                {exp.skills.slice(0, 2).map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </Col>
            <Col sm="12" md="12" lg="6">
              <ul className="mb-0">
                {exp.skills.slice(2).map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </Col>
          </Row>
        </Col>
      </Row>

      {exp.roles.map((r, i) => (
        <Row key={i}>
          <Col sm="12" md="3" lg="3">
            {i === 0 ? <h5>{strings.experience}</h5> : ""}
          </Col>
          <Col sm="12" md="9" lg="9">
            <RoleRow role={r} key={i} date={true} />
          </Col>
        </Row>
      ))}

      {exp.additional.map((r, i) => (
        <Row key={i}>
          <Col sm="12" md="3" lg="3">
            {i === 0 ? <h5>{strings.additional}</h5> : ""}
          </Col>
          <Col sm="12" md="9" lg="9">
            <RoleRow role={r} key={i} date={false} />
          </Col>
        </Row>
      ))}

      <Row className="mb-3">
        <Col sm="12" md="3" lg="3">
          <h5>
            <strong>{strings.education}</strong>
          </h5>
        </Col>
        <Col sm="12" md="9" lg="9">
          {exp.education.map((r, i) => (
            <div key={i}>
              <h5>{htmlToReact(r.company)}</h5>
              <Row className="mb-1">
                <Col xs="12" sm="6">
                  <strong>{htmlToReact(r.title)}</strong>
                </Col>
              </Row>
              <p className="mb-4">{htmlToReact(r.desc)}</p>
            </div>
          ))}
        </Col>
      </Row>

      <Row className="mb-3">
        <Col sm="12" md="3" lg="3">
          <h5>
            <strong>{strings.honors}</strong>
          </h5>
        </Col>
        <Col sm="12" md="9" lg="9">
          {exp.honors
            .sort((a, b) => Date.parse(a.date) - Date.parse(b.date))
            .map((h, i) => (
              <div key={i}>
                <Row className="mb-1">
                  <Col sm="12" lg="7">
                    <strong>{htmlToReact(h.title)}</strong>
                  </Col>
                  <Col sm="12" lg="5" className="text-left text-lg-right">
                    {h.entity}, {year(h.date)}
                  </Col>
                </Row>
                <p>{htmlToReact(h.description)}</p>
              </div>
            ))}
        </Col>
      </Row>
      <Row className="mb-3">
        <Col sm="12" md="3" lg="3">
          <h5>
            <strong>{strings.awards}</strong>
          </h5>
        </Col>
        <Col sm="12" md="9" lg="9">
          <ul>
            {exp.awards.map((a, i) => (
              <li key={i}>
                {htmlToReact(a.title)}, {a.entity},{" "}
                <PrintLink
                  href="/project/[id]"
                  hrefAs={`/project/${a.project}`}
                >
                  {projectQuery(a.project)?.title}
                </PrintLink>
                , {year(a.date)}
              </li>
            ))}
          </ul>
        </Col>
      </Row>
      <Row>
        <Col sm="12" md="3" lg="3">
          <h5>
            <strong>{strings.volunteering}</strong>
          </h5>
        </Col>
        <Col sm="12" md="9" lg="9">
          <ul>
            {exp.volunteering.map((v, i) => (
              <li key={i}>
                {htmlToReact(v.role)}, <a href={v.link}>{v.entity}</a>,{" "}
                {year(v.date)}
              </li>
            ))}
          </ul>
        </Col>
      </Row>
    </div>
  );
};

export default About;

export const getStaticProps: GetStaticProps = async (context) => {
  const projects = await import("../data/projects");
  const strings = await import("../data/strings");
  const exp = await import("../data/experience");

  return {
    props: {
      title: "Josh Santangelo",
      exp: exp.experience,
      strings: strings.about,
      description: strings.about.summary.join(" "),
      active: "about",
    },
  };
};
